version: '3.8'

services:

  app:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    restart: unless-stopped
    volumes:
      - .:/var/www
    networks:
      - app_net
    depends_on:
      - postgres
      - redis
      - kafka
      - elasticsearch
    command: php-fpm
    entrypoint: ["entrypoint.sh"]

  nginx:
    image: nginx:alpine
    restart: unless-stopped
    volumes:
      - .:/var/www
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "8000:80"
    networks:
      - app_net
    depends_on:
      - app

  postgres:
    image: postgres:16.2
    restart: always
    ports:
        - "5432:5432"
    environment:
        POSTGRES_USER: ${DB_USERNAME:-root}
        POSTGRES_PASSWORD: ${DB_PASSWORD:-root}
        POSTGRES_HOST_AUTH_METHOD: trust
    volumes:
        - ./db_storage:/var/lib/postgresql/data
        - ./docker/postgres:/docker-entrypoint-initdb.d
    networks:
      - app_net

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    networks:
      - app_net

  zookeeper:
    image: confluentinc/cp-zookeeper:7.6.0
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    networks:
      - app_net

  kafka:
    image: confluentinc/cp-kafka:7.6.0
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    networks:
      - app_net

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.19.0
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
    ports:
      - "9200:9200"
    networks:
      - app_net
    volumes:
      - esdata:/usr/share/elasticsearch/data

  kibana:
    image: docker.elastic.co/kibana/kibana:8.19.0
    ports:
      - "5601:5601"
    environment:
      ELASTICSEARCH_HOSTS: http://elasticsearch:9200
    depends_on:
      - elasticsearch
    networks:
      - app_net

networks:
  app_net:

volumes:
  esdata:
